<<<<<<< HEAD
const courses = [
{id: 1,
thumbnail: "/images/fluent-english.jpg",
title: "Fluent English in 30 Days",
creator: "Anjali Roy",
language: "English",
level: "Beginner",
hours: 6},
{id: 2,
thumbnail: "/images/english-grammar-basics.jpg",
title: "English Grammar Made Simple",
creator: "Learn with Arjun",
language: "English",
level: "All levels",
hours: 4},
{id: 3,
thumbnail: "/images/german-a1-complete.jpg",
title: "Complete A1 German",
creator: "Daniel Weber",
language: "German",
level: "A1",
hours: 8},
{id: 4,
thumbnail: "/images/german-pronunciation.jpg",
title: "German Pronunciation Essentials",
creator: "German Basics",
language: "German",
level: "A1–B1",
hours: 3},
{id: 5,
thumbnail: "/images/spanish-beginner.jpg",
title: "Spanish for Absolute Beginners",
creator: "Maria Torres",
language: "Spanish",
level: "Beginner",
hours: 5},
{id: 6,
thumbnail: "/images/spanish-grammar.jpg",
title: "Spanish Grammar Step by Step",
creator: "Aprende con Sofia",
language: "Spanish",
level: "A1–A2",
hours: 4},
{id: 7,
thumbnail: "/images/english-conversation.jpg",
title: "Daily English Conversation Pack",
creator: "SpeakEasy English",
language: "English",
level: "Beginner",
hours: 3.5},
{id: 8,
thumbnail: "/images/german-speaking.jpg",
title: "German Speaking Practice",
creator: "Deutsch mit Lea",
language: "German",
level: "A1–B1",
hours: 5}
];
=======
import data from "./courses.json";

const courses = Array.isArray(data.courses) ? data.courses : [];

export default courses;
>>>>>>> 4e99a378bb7ed1657b105db911e12f00006e4076
